const Timeline = () => (
  <svg
    viewBox="0 0 811 65"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <text x="0" y="10" fill="var(--font-color)">
      TIMELINE &rarr;
    </text>
    <circle
      cx="15"
      cy="30"
      r="15"
      fill="#da2497"
      id="dragNavigator"
    />
    <line
      x1="39.9674"
      y1="29.5"
      x2="806.033"
      y2="29.5"
      stroke="var(--font-color)"
    />
    <circle
      id="circle-1"
      className="circle"
      cx="45"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-2"
      className="circle"
      cx="91"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-3"
      className="circle"
      cx="137"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-4"
      className="circle"
      cx="183"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-5"
      className="circle"
      cx="229"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-6"
      className="circle"
      cx="274.58"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-7"
      className="circle"
      cx="321"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-8"
      className="circle"
      cx="367"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-9"
      className="circle"
      cx="413"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-10"
      className="circle"
      cx="459"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-11"
      className="circle"
      cx="505"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-12"
      className="circle"
      cx="551"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-13"
      className="circle"
      cx="597"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-14"
      className="circle"
      cx="643"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-15"
      className="circle"
      cx="689"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <circle
      id="circle-16"
      className="circle"
      cx="735"
      cy="30"
      r="5"
      fill="var(--font-color)"
    />
    <text x="775" y="15" fill="var(--font-color)">
      2020
    </text>
  </svg>
);

export default Timeline;
